### ISSUE TITLE
Possible to build to arm64?

### ISSUE THREAD

**Issue by Egrirt** [sabrsorensen/alpine-plex_autoscan#2]
I love plex autoscan, but recently I moved my plex server to a RPi 4 and I would like to put as much stuff in docker as possible. Would it be possible to add arm64 builds also to the docker hub?

Thanks in advance

**Comment by sabrsorensen** [comment]
I'm not familiar with building for arm64, but I can look into this. The rclone image I base this on doesn't provide an arm64 variant, so I'm leaning towards switching to an arm64 Debian image and handling the rclone installation in this image as well. I'll follow up here when I have something.

**Comment by Egrirt** [comment]
> I'm not familiar with building for arm64, but I can look into this. The rclone image I base this on doesn't provide an arm64 variant, so I'm leaning towards switching to an arm64 Debian image and handling the rclone installation in this image as well. I'll follow up here when I have something.

Sounds good, thanks allot :)

**Comment by sabrsorensen** [comment]
@Deuxgod I believe I've setup a workflow to generate arm64 and arm-v7 images along with amd64, if you still need this. Check out the :arm64 tag, or I believe that docker will automatically pull the correct image for your architecture if I've configured the :latest manifest correctly: https://hub.docker.com/r/sabrsorensen/alpine-plex_autoscan/tags
