### ISSUE TITLE
Docker unhealthy

### ISSUE THREAD

**Issue by nickmers** [sabrsorensen/alpine-plex_autoscan#3]
Since two days ago dont work for me and other users. I didnt do nothing but I dont know what happen. Since yesterday, always work good. Sorry for my english.

![Screenshot_1](https://user-images.githubusercontent.com/52675796/88451225-557cb680-ce55-11ea-8132-8b78a448e203.png)
![Screenshot_3](https://user-images.githubusercontent.com/52675796/88451226-557cb680-ce55-11ea-860b-086c1e4d8a70.png)

**Comment by doob187** [comment]
You can also do follow 
```
sudo mkdir -p <<>>>>/config/rclone 
sudo cp -rv <<>>>>/rclone.conf <<>>>>/ plexautoscan/config/rclone/ 
sudo chown -cR 1000:1000  <<>>/config/rclone
sudo docker restart plexautoscan
```

**Comment by sabrsorensen** [comment]
@nickmers that error message indicates that you don't have your rclone.conf mounted in the container at the location you have specified in the RCLONE.CONFIG field of the plex_autoscan config.json you're using. Check your container volume mappings to make sure you're passing in the appropriate rclone.conf and you have the correct container filepath specified in your config.json.
